version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: jc-hair-studio-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: jc-hair-studio-ecommerce
    volumes:
      - mongodb_data:/data/db
    networks:
      - jc-hair-network

  mongo-express:
    image: mongo-express:1.0.0-alpha
    container_name: jc-hair-studio-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongodb
    networks:
      - jc-hair-network

volumes:
  mongodb_data:
    driver: local

networks:
  jc-hair-network:
    driver: bridge