[build]
  publish = ".next"
  command = "npm run build:netlify"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefix=/opt/buildhome/cache/netlify_cache"
  NODE_OPTIONS = "--max-old-space-size=4096"
  SKIP_TYPE_CHECK = "true"
  SKIP_LINT = "true"
  NEXT_TELEMETRY_DISABLED = "1"
  NETLIFY = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = ".netlify/functions/"
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[redirects]]
  from = "/admin"
  to = "/admin/dashboard"
  status = 302

# API Routes handling for Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Fallback for Next.js routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200