#!/bin/bash

###############################################################################
# Monitoring Setup Script - JC Hair Studio
# Set up comprehensive uptime and change detection monitoring
###############################################################################

set -e

echo "=================================="
echo "MONITORING SETUP - JC HAIR STUDIO"
echo "=================================="
echo ""

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

DOMAIN="jchairstudios62.xyz"

echo -e "${BLUE}FREE UPTIME MONITORING SERVICES${NC}"
echo ""

echo "1. UPTIMEROBOT (Recommended - Free)"
echo "   - URL: https://uptimerobot.com"
echo "   - Features: 50 monitors, 5-min checks, email alerts"
echo "   - Setup:"
echo "     a) Sign up (free)"
echo "     b) Add monitor: https://${DOMAIN}"
echo "     c) Set check interval: 5 minutes"
echo "     d) Add alert contacts (email, SMS, webhook)"
echo "     e) Add keyword monitor for '200 OK' or specific content"
echo ""

echo "2. FRESHPING (Alternative)"
echo "   - URL: https://www.freshworks.com/website-monitoring/"
echo "   - Features: 50 monitors, 1-min checks, multiple locations"
echo "   - Setup similar to UptimeRobot"
echo ""

echo "3. STATUSCAKE (Alternative)"
echo "   - URL: https://www.statuscake.com"
echo "   - Features: 10 monitors, 5-min checks, SSL monitoring"
echo "   - Setup similar to UptimeRobot"
echo ""

echo -e "${BLUE}GOOGLE SEARCH CONSOLE MONITORING${NC}"
echo ""
echo "Essential for SEO and indexing:"
echo "  1. Visit: https://search.google.com/search-console"
echo "  2. Add property: ${DOMAIN}"
echo "  3. Verify ownership (DNS TXT record method recommended)"
echo "  4. Submit sitemap: https://${DOMAIN}/sitemap.xml"
echo "  5. Enable email alerts for:"
echo "     - Indexing issues"
echo "     - Mobile usability errors"
echo "     - Security issues"
echo "     - Manual actions"
echo ""

echo -e "${BLUE}BING WEBMASTER TOOLS${NC}"
echo ""
echo "  1. Visit: https://www.bing.com/webmasters"
echo "  2. Add site: ${DOMAIN}"
echo "  3. Verify ownership"
echo "  4. Submit sitemap: https://${DOMAIN}/sitemap.xml"
echo "  5. Enable URL inspection tool"
echo ""

echo -e "${BLUE}CHANGE DETECTION MONITORING${NC}"
echo ""
echo "Monitor page changes and content updates:"
echo ""
echo "1. VISUALPING (Recommended - Free)"
echo "   - URL: https://visualping.io"
echo "   - Features: Visual change detection, email alerts"
echo "   - Monitor these pages:"
echo "     - https://${DOMAIN}/"
echo "     - https://${DOMAIN}/categoria/tratamentos-capilares"
echo "     - https://${DOMAIN}/sobre"
echo ""

echo "2. CHANGELLY (Alternative)"
echo "   - URL: https://changelly.io"
echo "   - Features: Content change detection"
echo ""

echo -e "${BLUE}ANALYTICS & PERFORMANCE MONITORING${NC}"
echo ""
echo "1. GOOGLE ANALYTICS 4"
echo "   - URL: https://analytics.google.com"
echo "   - Track: Traffic, conversions, user behavior"
echo "   - Set up goals and events"
echo ""

echo "2. GOOGLE PAGESPEED INSIGHTS"
echo "   - URL: https://pagespeed.web.dev"
echo "   - Test: https://${DOMAIN}"
echo "   - Monitor Core Web Vitals"
echo ""

echo "3. VERCEL ANALYTICS (Built-in)"
echo "   - Dashboard: https://vercel.com/dashboard/analytics"
echo "   - Real-time traffic monitoring"
echo "   - Web Vitals tracking"
echo ""

echo -e "${BLUE}SSL/TLS MONITORING${NC}"
echo ""
echo "1. SSL LABS"
echo "   - URL: https://www.ssllabs.com/ssltest/"
echo "   - Test: ${DOMAIN}"
echo "   - Grade: A+ recommended"
echo ""

echo "2. CERTIFICATE EXPIRY MONITORING"
echo "   - Most uptime monitors include SSL expiry alerts"
echo "   - Current expiry: $(echo | openssl s_client -servername ${DOMAIN} -connect ${DOMAIN}:443 2>/dev/null | openssl x509 -noout -dates | grep notAfter | cut -d'=' -f2)"
echo ""

echo -e "${BLUE}AUTOMATED MONITORING SCRIPTS${NC}"
echo ""
echo "Run these scripts regularly (set up cron jobs):"
echo ""
echo "Daily:"
echo "  - bash scripts/monitor-indexing.sh"
echo "  - bash scripts/check-site-health.sh (create)"
echo ""
echo "Weekly:"
echo "  - bash scripts/ping-search-engines.sh"
echo "  - bash scripts/audit-seo.sh (create)"
echo ""
echo "Monthly:"
echo "  - bash scripts/full-site-audit.sh (create)"
echo ""

echo -e "${BLUE}CRON JOB SETUP (Optional)${NC}"
echo ""
echo "To automate monitoring, add these to crontab:"
echo ""
echo "# Daily monitoring at 9 AM"
echo "0 9 * * * cd /path/to/project && bash scripts/monitor-indexing.sh >> logs/monitoring.log 2>&1"
echo ""
echo "# Weekly sitemap submission (Sunday 2 AM)"
echo "0 2 * * 0 cd /path/to/project && bash scripts/ping-search-engines.sh >> logs/seo-pings.log 2>&1"
echo ""

echo -e "${BLUE}ALERTING CHANNELS${NC}"
echo ""
echo "Recommended alert methods:"
echo "  1. Email (primary)"
echo "  2. SMS (critical issues)"
echo "  3. Slack/Discord webhook (team notifications)"
echo "  4. PagerDuty (enterprise option)"
echo ""

echo -e "${GREEN}=================================="
echo "MONITORING CHECKLIST"
echo "==================================${NC}"
echo ""
echo "Essential (Do Now):"
echo "  [ ] Set up UptimeRobot for uptime monitoring"
echo "  [ ] Add site to Google Search Console"
echo "  [ ] Add site to Bing Webmaster Tools"
echo "  [ ] Set up SSL certificate expiry alerts"
echo ""
echo "Important (This Week):"
echo "  [ ] Configure Google Analytics 4"
echo "  [ ] Set up VisualPing for page change detection"
echo "  [ ] Test all alert channels"
echo "  [ ] Run PageSpeed Insights baseline test"
echo ""
echo "Nice to Have:"
echo "  [ ] Set up automated cron jobs"
echo "  [ ] Configure Vercel Analytics"
echo "  [ ] Create custom monitoring dashboard"
echo "  [ ] Set up competitor monitoring"
echo ""

echo -e "${BLUE}MONITORING DASHBOARD CREATION${NC}"
echo ""
echo "Consider creating a simple monitoring dashboard:"
echo "  - URL: https://statsig.com (free)"
echo "  - URL: https://grafana.com (self-hosted)"
echo "  - URL: https://www.datadoghq.com (enterprise)"
echo ""

echo -e "${GREEN}Setup complete! Follow the checklist above.${NC}"
echo ""
